### ISSUE TITLE
Add link to MEG questionnaire on meg-contraindications.html page

### ISSUE THREAD

**Issue by gbirot** [fcbg-hnp-meeg/meg-wiki#22]
https://fondationcampusbiotech.sharepoint.com/:w:/s/FCBG_PROJ_010_HNP_MEG/EaQOqEu-5PBHtjoMabmczFcBdCyLSlBrwxecZCv21jtkog?e=WMckTB
https://fondationcampusbiotech.sharepoint.com/:w:/s/FCBG_PROJ_010_HNP_MEG/EU1tszqm0LlJj-N1liNpjGsBaEuZxYh1Y4cWUXp3agM0aA?e=VTOYLa

**Comment by mscheltienne** [comment]
@gbirot Questionnaires to be filled by the researcher with the participant?
French and English version of the same questionnaire? (in which case let's also have them match).

**Comment by gbirot** [comment]
Last version is the one in french. I will edit the english version accordingly.

**Comment by gbirot** [comment]
Updated versions to be added:
https://fondationcampusbiotech.sharepoint.com/:w:/s/FCBG_PROJ_010_HNP_MEG/EaQOqEu-5PBHtjoMabmczFcBdCyLSlBrwxecZCv21jtkog?e=Kss8m8
https://fondationcampusbiotech.sharepoint.com/:w:/s/FCBG_PROJ_010_HNP_MEG/EXOFL4nMa51KpFgVudVjBv0BynltY1rae98A7IHmEnZ6UQ?e=Uqr5ff

**Comment by mscheltienne** [comment]
@gbirot Done, I turned the docx into PDFs with editable fields to make it easier to fill on computer/tablets.
Render: https://meg-wiki.hnp.fcbg.ch/meg-contraindications.html

The source is now present in the repository:
- docs in `pdfs/questionnaires`
- PDFs (which can be further edited, including the forms fields, in Adbove) in `doc/_static/questionnaires`
Thus, I think it would be best to delete the 2 docs on the sharepoint to limit duplication and simplify future changes.
